// <auto-generated />
using System;
using HomeBudgetManager.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBudgetManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123175447_UpdateRecurringTransactions")]
    partial class UpdateRecurringTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransactionCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category_name");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_id");

                    b.Property<int>("CompanyAdminId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_admin_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("house_description");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("house_join_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("house_name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyAdminId");

                    b.ToTable("houses");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBRecurringOperations", b =>
                {
                    b.Property<int>("TransactionPatternId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repetable_transaction_id");

                    b.Property<int>("IntervalType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_type");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("NextRunDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_run_date");

                    b.HasKey("TransactionPatternId");

                    b.ToTable("repetable_transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBFinancialOperations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_description");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_for_house_id");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_is_repeatable");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_type");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<decimal>("IntervalValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_value");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_email");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_house_id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_password");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransactionCategories", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "User")
                        .WithMany("Categories")
                        .HasForeignKey("CompanyId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCompany", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "CompanyAdmin")
                        .WithMany()
                        .HasForeignKey("CompanyAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyAdmin");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBRecurringOperations", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBFinancialOperations", "Transaction")
                        .WithOne("RepetableTransaction")
                        .HasForeignKey("HomeBudgetManager.Core.DBTables.DBRecurringOperations", "TransactionPatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBFinancialOperations", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBTransactionCategories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCompany", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "Company")
                        .WithMany("Members")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCompany", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBFinancialOperations", b =>
                {
                    b.Navigation("RepetableTransaction");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCompany", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
