// <auto-generated />
using System;
using HomeBudgetManager.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBudgetManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260125142226_AddTitleToTransaction")]
    partial class AddTitleToTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_id");

                    b.Property<int>("AdminId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_admin_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("house_description");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("house_join_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("house_name");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("houses");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBRepetableTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("FrequencyUnit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frequency_unit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("NextRunDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_run_date");

                    b.Property<int?>("TransactionId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionInterval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_interval");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("TransactionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TransactionId1");

                    b.HasIndex("UserId");

                    b.ToTable("repetable_transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_description");

                    b.Property<int?>("HouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_for_house_id");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_is_repeatable");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_title");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_type");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_value");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HouseId");

                    b.HasIndex("UserId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_email");

                    b.Property<int?>("HouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_house_id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_password");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HouseId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCategory", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBUser", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBUser", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBRepetableTransaction", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBTransaction", null)
                        .WithOne("RepetableTransaction")
                        .HasForeignKey("HomeBudgetManager.Core.DBTables.DBRepetableTransaction", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId1");

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBHouse", "House")
                        .WithMany()
                        .HasForeignKey("HouseId");

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBUser", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("House");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBHouse", "House")
                        .WithMany("Members")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("House");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.Navigation("RepetableTransaction");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
