// <auto-generated />
using System;
using HomeBudgetManager.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBudgetManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DBContractorDBInvoice", b =>
                {
                    b.Property<int>("InvoicesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelatedContractorInvoicesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoicesId", "RelatedContractorInvoicesId");

                    b.HasIndex("RelatedContractorInvoicesId");

                    b.ToTable("DBContractorDBInvoice");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("company_id");

                    b.Property<int>("CompanyAdminId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("company_admin_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("company_description");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("company_join_code");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_nip");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("company_name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyAdminId");

                    b.ToTable("company");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBContractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("contractor_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("company_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("contractor_name");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("contractor_tax_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("contractors");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_company_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_password");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_role");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBFinancialOperations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_description");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_is_repeatable");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_title");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_type");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_value");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("FinancialOperations");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("company_id");

                    b.Property<int>("ContractorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contractor_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("issue_date");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_method");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_status");

                    b.Property<decimal>("TotalGross")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_gross");

                    b.Property<decimal>("TotalNet")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_net");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_type");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractorId");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBRecurringOperations", b =>
                {
                    b.Property<int>("TransactionPatternId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pattern_id");

                    b.Property<int>("IntervalType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IntervalType");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextRunDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_run_date");

                    b.HasKey("TransactionPatternId");

                    b.ToTable("repetable_transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Guest"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Accountant"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CompanyAdmin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SystemAdmin"
                        });
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransactionCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("company_id");

                    b.Property<int?>("DBEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category_name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DBEmployeeId");

                    b.ToTable("transaction_categories");
                });

            modelBuilder.Entity("DBContractorDBInvoice", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBInvoice", null)
                        .WithMany()
                        .HasForeignKey("InvoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBContractor", null)
                        .WithMany()
                        .HasForeignKey("RelatedContractorInvoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCompany", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBEmployee", "CompanyAdmin")
                        .WithMany()
                        .HasForeignKey("CompanyAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyAdmin");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBContractor", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBEmployee", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "Company")
                        .WithMany("Members")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBFinancialOperations", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBTransactionCategories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBEmployee", "Employee")
                        .WithMany("Transactions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBInvoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBInvoice", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBContractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBRecurringOperations", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBFinancialOperations", "Transaction")
                        .WithOne("RecurringOperation")
                        .HasForeignKey("HomeBudgetManager.Core.DBTables.DBRecurringOperations", "TransactionPatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransactionCategories", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBEmployee", null)
                        .WithMany("Categories")
                        .HasForeignKey("DBEmployeeId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCompany", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBEmployee", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBFinancialOperations", b =>
                {
                    b.Navigation("RecurringOperation");
                });
#pragma warning restore 612, 618
        }
    }
}
